adding fe check retry and certificates in fe container image

diff --git a/kubernetes-manifests/loadgenerator.yaml b/kubernetes-manifests/loadgenerator.yaml
--- a/kubernetes-manifests/loadgenerator.yaml
+++ b/kubernetes-manifests/loadgenerator.yaml
@@ -35,11 +35,22 @@ spec:
             - /bin/sh
             - -exc
             - |
-              echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
-              STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
-              if test $STATUSCODE -ne 200; then
-                  echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
-                  exit 1
+              retries=10
+              count=0
+              while [ $count -lt $retries ]; do
+                echo "Init container pinging frontend: ${FRONTEND_ADDR}... (Attempt $((count + 1)))"
+                STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+                if [ $STATUSCODE -eq 200 ]; then
+                  echo "Success: Frontend is reachable - Status code: ${STATUSCODE}"
+                  break
+                fi
+                echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+                count=$((count + 1))
+                sleep 5  # Adjust sleep duration as needed
+              done
+              if [ $count -eq $retries ]; then
+                echo "Init container reached maximum retries, exiting with failure."
+                exit 1
               fi
           name: frontend-check
           image: busybox:latest
